name: Auto Generator

on:
  push:
    branches:
      - AutoGenerator
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  Auto_Generator:
    runs-on: ubuntu-latest
    outputs:
      changes_detected: ${{ steps.git_auto_commit.outputs.changes_detected }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - name: Auto Generator
        run: 'docker run -v .:/output -v $PWD/AutoGenerator/AutoGenerator/appsettings.json:/app/appsettings.json ghcr.io/youtubeclipplaylist/playlistautogenerator'

      - name: Git Auto Commit
        id: git_auto_commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: AutoGenerator
          file_pattern: AutoGenerator
          commit_message: 'Github Action: Auto Generator'
          commit_user_name: Github Action Bot # defaults to "GitHub Actions"
          commit_author: Github Action Bot <actions@github.com> # defaults to author of the commit that triggered the run

  Auto_PR:
    needs: Auto_Generator
    if: needs.Auto_Generator.outputs.changes_detected == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: AutoGenerator

      - name: Git Auto PR
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          # be explicit about branches
          source_branch: 'AutoGenerator'
          destination_branch: 'master'
          pr_title: 'AutoGenerator to master auto PR'
          pr_body: ':robot: Automated PR from **AutoGenerator** to **master**'
          pr_label: 'automerge'
