name: Auto Generator

on:
  # push:
  #   branches: [ master ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  Auto_Generator:
    runs-on: windows-latest # dotnet SDK built-in

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Auto Generator
        shell: cmd
        run: "call .github\\workflows\\AutoGenerator.exe"

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: AutoGenerator
          commit_message: 'Github Action: Auto Generator'
          commit_user_name: Github Action Bot # defaults to "GitHub Actions"
          commit_author: Github Action Bot <actions@github.com> # defaults to author of the commit that triggered the run

  Auto_PR:
    needs: Auto_Generator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: AutoGenerator

      - name: Git Auto PR
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          # be explicit about branches
          source_branch: 'AutoGenerator'
          destination_branch: 'master'
          pr_title: 'AutoGenerator to master auto PR'
          pr_body: ':robot: Automated PR from **AutoGenerator** to **master**'
