name: CreateRadioQTamaSubtitles

on:
  push:
    branches: [ QuonTama ]
  schedule:
    - cron:  '* 0 * * *'
  workflow_dispatch:

jobs:
  CreateRadioQTamaSubtitles_Action:
    runs-on: windows-latest # dotnet SDK built-in

    steps:
      - uses: actions/checkout@v2
        with:
          ref: QuonTama

      # If no changes have been made, the program will exit with error code 80, and terminate CI.
      - name: Fetch and recreate RadioQTama subtitles
        shell: cmd
        run: "call .github\\workflows\\CreateRadioQTamaSubtitles.exe"

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: QuonTama
          commit_message: "Github Action: Fetch and recreate RadioQTama subtitles"
          commit_user_name: Github Action Bot # defaults to "GitHub Actions"
          commit_author: Github Action Bot <actions@github.com> # defaults to author of the commit that triggered the run
