name: JSON Syntax Check

on:
  pull_request:
    branches-ignore:
      - jim60105/AutoGenerator

jobs:
  json-syntax-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: json-syntax-check
        uses: limitusus/json-syntax-check@v1
        with:
          pattern: "\\.jsonc$"
